sudo: required
services:
  - docker
before_install:
  - docker build -t yevheniibereziuk/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yevheniibereziuk/docker-react-test npm run test

after_success:
  - docker build -t yevheniibereziuk/multi-client ./client
  - docker build -t yevheniibereziuk/multi-nginx ./nginx
  - docker build -t yevheniibereziuk/multi-server ./server
  - docker build -t yevheniibereziuk/multi-worker ./worker

