version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /complex/node_modules
      - ./server:/complex
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true   
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /complex/node_modules
      - ./client:/complex
    user: "node"

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /complex/node_modules
      - ./worker:/complex
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

